Create aws-marketplace-announce.md
flowforge/website pull request #1049
Opened 2023-08-18 14:24 UTC by iskerrett

AWS Marketplace announcement.

2023-08-18 14:49 UTC, MarianRaphael approved these changes
In addition, I would add the link to our AWS offering:
https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

2023-08-18 15:04 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +---
```suggestion
---

```

2023-08-18 15:04 UTC, hardillb commented
Will want to include a link to the docs as well which will be here 

https://flowfuse.com/docs/install/docker/aws-marketpace/ 

when https://github.com/flowforge/flowforge/pull/2618 is merged

2023-08-18 15:08 UTC, iskerrett commented
> In addition, I would add the link to our AWS offering: https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

Yes of course. :-)

2023-08-18 15:12 UTC, ZJvandeWeg commented
@MarianRaphael Can you create a doc update on the main repo with a backport next week?

2023-08-18 15:19 UTC, ZJvandeWeg requested changes

2023-08-18 15:19 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +image: blog/2023/08/images/UNS/UNS-Headline.svg
Consider an image from unsplash if you want to publish today: https://unsplash.com/photos/M2524ncJQ40

2023-08-18 15:19 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +FlowFuse on AWS Marketplace is available [immediately](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa). Please refer to our [documentation
```suggestion
FlowFuse on AWS Marketplace is available [immediately](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa). Please refer to our [documentation](/docs/install/docker/aws-marketpace/) and give it a try and let us know what you think.
```

2023-08-18 15:19 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +Today, we are excited to announce that FlowFuse is now available from the [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa
Nit, but I like this a bit better

```suggestion
Many customers want to run FlowFuse in their own cloud environment, AWS being a great example. Today we're excited to announce that FlowFuse is now available from the [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa). This makes it very easy for customers to install and run Node-RED and FlowFuse within minutes.

```

2023-08-18 15:19 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +Customers can easily upgrade to the premium or enterprise tier by obtaining a commercial license from FlowFuse.
```suggestion
Customers can easily upgrade to the premium or enterprise tier by obtaining a commercial license from FlowFuse. To understand what FlowFuse can do for your use-case, please [book a demo](/book-demo).
```

2023-08-18 16:59 UTC, ZJvandeWeg approved these changes

2023-08-20 10:42 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +    - news
```suggestion
    - news
    - flowfuse
```

2023-08-21 06:46 UTC, ZJvandeWeg requested changes

2023-08-21 06:46 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +date: 2023-08-18
```suggestion
date: 2023-08-21
```

2023-08-21 09:21 UTC, hardillb commented
Docs will go live with the next Website publish

https://github.com/flowforge/flowforge/pull/2622

2023-08-21 13:34 UTC, ZJvandeWeg commented
I've rebased this PR and hopefully that fixes the doc link being broken

2023-08-21 14:01 UTC, hardillb commented on src/blog/2023/08/aws-marketplace-announce.md
> +FlowFuse on AWS Marketplace is available [immediately](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa). Please refer to our [documentation
```suggestion
FlowFuse on AWS Marketplace is available [immediately](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa). Please refer to our [documentation](/docs/install/docker/aws-marketplace/) and give it a try and let us know what you think.
```

2023-08-21 14:22 UTC, ZJvandeWeg commented on src/blog/2023/08/aws-marketplace-announce.md
> +FlowFuse on AWS Marketplace is available [immediately](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa). Please refer to our [documentation
```suggestion
FlowFuse on AWS Marketplace is available [immediately](https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa). Please refer to our [documentation](/docs/install/docker/aws-marketplace/#installing-flowfuse-from-aws-market-place) and give it a try and let us know what you think.
```

2023-08-21 14:22 UTC, ZJvandeWeg approved these changes

2023-08-21 14:27 UTC, merged