Add improved header styling
flowforge/website pull request #215
Opened 2022-10-22 15:46 UTC by joepavitt

**Before:**
<img width="706" alt="Screenshot 2022-10-22 at 16 31 13" src="https://user-images.githubusercontent.com/99246719/197348465-99481572-a05e-42d7-a1e0-c7c52b6de415.png">

**After:**
<img width="688" alt="Screenshot 2022-10-22 at 16 30 35" src="https://user-images.githubusercontent.com/99246719/197348463-a079987d-baa7-4cad-a4d2-67b727b83eb9.png">

2022-10-22 15:50 UTC, joepavitt commented
Whilst these styling changes do improve readability, we may want to consider adding numeric heading separators too (Numeric, Alphabetical or Roman), which could be auto-generated in `./src/_includes/layouts/handbook.njk` where we currently auto-generate the ToC.

So:
```markdown
# Heading A
Content Content Content

## Heading B
Content Content Content

## Heading C
Content Content Content
```

would be auto-generated as:

```html
<h1>I. Heading A</h1>
<p>Content Content Content</p>
<h2>I.I Heading B</h2>
<p>Content Content Content</p>
<h2>I.II Heading C</h2>
<p>Content Content Content</p>
```

This may also make a short term assist for https://github.com/flowforge/website/issues/193 to distinguish between the ToC Headers and overall navigation headers

2022-10-24 10:03 UTC, Pezmc requested changes
I think some test code might have slipped though.

I'm onboard to the numeric heading suggestion!

2022-10-24 10:03 UTC, Pezmc commented on src/css/style.nohero.css
> +    color: red;
This looks like debugging code to me!

2022-10-25 07:53 UTC, joepavitt commented on src/css/style.nohero.css
> +    color: red;
Right you are - poor form - fixed

2022-10-25 12:55 UTC, Pezmc approved these changes

2022-10-25 12:55 UTC, merged