March webinar page
flowforge/website pull request #441
Opened 2023-02-22 19:50 UTC by iskerrett

## Description

March webinar page 

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2023-02-22 19:54 UTC, iskerrett commented
@joepavitt for some reason this page doesn't show up on the main webinar page when I am looking at it locally.   I don't want to publish until after the webinar on Feb 23 but can you take a look?

@knolleary can you please review the text to make sure you are okay with it.

2023-02-23 09:27 UTC, joepavitt commented
> for some reason this page doesn't show up on the main webinar page when I am looking at it locally. 

this is by design, although I'm happy to change it. I built it so that it only ever showed the next upcoming Webinar & AMA session, I ddi it this way so that you could plan ahead, add as many future sessions as you'd like, and it would automatically show the "next" Webinar automatically once the other was out of the way, rather than having to hold off publishing future webinars until after the first one was out of the way.

2023-02-23 10:34 UTC, knolleary requested changes

2023-02-23 10:34 UTC, knolleary commented on src/webinars/2023/introduction-to-flowforge.md
> +**Join Nick O'Leary, CTO of FlowForge and co-creator of Node-RED, as he presents an in-depth webinar showcasing how FlowForge delivers reliable and secure Node-RED applications in a continuous, colla
```suggestion
**Join Nick O'Leary, CTO of FlowForge and co-creator of Node-RED, as he presents an in-depth webinar showcasing how FlowForge delivers reliable and secure Node-RED applications in a continuous, collaborative manner.**
```

2023-02-23 10:34 UTC, knolleary commented on src/webinars/2023/introduction-to-flowforge.md
> +subtitle: Join Flowforge's CTO Nick O'Leary for an introduction to Flowforge and how it provides DevOps for Node-RED.
```suggestion
subtitle: Join FlowForge's CTO Nick O'Leary for an introduction to FlowForge and how it provides DevOps for Node-RED.
```

2023-02-23 10:34 UTC, knolleary commented on src/webinars/2023/introduction-to-flowforge.md
> +hosts: ["nick-o'leary"]
```suggestion
hosts: ["nick-oleary"]
```

2023-02-24 16:52 UTC, joepavitt approved these changes

2023-02-24 16:52 UTC, merged