HA Blog post
flowforge/website pull request #717
Opened 2023-05-07 20:49 UTC by knolleary

## Description

Closes https://github.com/flowforge/content/issues/96

Needs a social tile creating - will raise art request and link to the issue.

2023-05-08 06:45 UTC, MarianRaphael approved these changes

2023-05-08 06:45 UTC, MarianRaphael commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +verage with each update. If you have multiple instances, then the node will be
```suggestion
average with each update. If you have multiple instances, then the node will be
```

2023-05-08 06:45 UTC, MarianRaphael commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +We've indentified our initial set of tasks and changes to how we'll run Node-RED
```suggestion
We've identified our initial set of tasks and changes to how we'll run Node-RED
```

2023-05-09 09:59 UTC, robmarcer approved these changes

2023-05-09 10:12 UTC, robmarcer requested changes

2023-05-09 10:12 UTC, robmarcer commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +to have a high degree of availability, reliability and scalability. Following up
```suggestion
to have a high degree of availability, reliability, and scalability. Following up
```

2023-05-09 10:12 UTC, robmarcer commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +doesn’t provide a way to atomically update values - so you can get into classic
```suggestion
doesn’t provide a way to automatically update values - so you can get into classic
```

2023-05-09 10:12 UTC, robmarcer commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +you want to have multiple instances sharing the same store. The context api
```suggestion
you want to have multiple instances sharing the same store. The context API
```

2023-05-09 10:12 UTC, robmarcer commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +api.
```suggestion
API.
```

2023-05-09 10:12 UTC, robmarcer commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +In an HA world, once you have multiple instances running behind an HTTP load
```suggestion
In a HA world, once you have multiple instances running behind an HTTP load
```

2023-05-09 10:12 UTC, robmarcer commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +solve with the current Node-RED APIs - and something we’ll be working both in
```suggestion
solve with the current Node-RED APIs - and something we’ll be working on both in
```

2023-05-09 10:27 UTC, knolleary commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +doesn’t provide a way to atomically update values - so you can get into classic
No - atomically is the right word.

2023-05-09 10:31 UTC, robmarcer approved these changes

2023-05-09 10:49 UTC, robmarcer commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +our [previous post on the subject](../02/highly-available-node-red.md), in this
```suggestion
our [previous post on the subject](/blog/02/highly-available-node-red), in this
```

2023-05-31 15:19 UTC, iskerrett commented
This post seems ready for publishing.  @knolleary do you agree?  @ZJvandeWeg you are the last reviewer

2023-05-31 15:22 UTC, MarianRaphael requested changes

2023-06-01 12:14 UTC, ZJvandeWeg commented
I'll first let @knolleary decide if this is indeed words he's comfortable with, but I think this blog would help and I'm supportive of merging sooner rather than later

2023-06-02 08:25 UTC, MarianRaphael approved these changes

2023-06-02 08:28 UTC, knolleary commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +date: 2023-05-08 12:00:00
```suggestion
date: 2023-06-02 12:00:00
```

2023-06-02 08:29 UTC, knolleary commented on src/blog/2023/05/bringing-high-availability-to-node-red.md
> +our [previous post on the subject](/blog/02/highly-available-node-red), in this
```suggestion
our [previous post on the subject](/blog/2023/02/highly-available-node-red/), in this
```

2023-06-02 11:27 UTC, merged