1 7 release notes
flowforge/website pull request #735
Opened 2023-05-10 13:07 UTC by MarianRaphael

## Description
1.7 Release notes highlights:

- Presenting Remote Node-RED Editor Access for Devices
- Device Status Visualisation

2023-05-10 13:29 UTC, robmarcer requested changes

2023-05-10 13:29 UTC, robmarcer commented on src/blog/2023/05/flowforge-1-7-released.md
> +The new FlowForge 1.7 adds new support for accesing the Node-RED Editor on Devices via FlowForge
```suggestion
FlowForge 1.7 adds new support for accessing the Node-RED Editor on Devices via FlowForge
```

2023-05-10 13:29 UTC, robmarcer commented on src/blog/2023/05/flowforge-1-7-released.md
> +[FlowForge Cloud](https://app.flowforge.com) is already running 1.6.
```suggestion
[FlowForge Cloud](https://app.flowforge.com) is already running 1.7.
```

2023-05-10 13:29 UTC, robmarcer commented on src/blog/2023/05/flowforge-1-7-released.md
> +## Boosts Node-RED Instance Reliability
```suggestion
## Auto Restart for Hung Node-RED Instances
```

2023-05-10 13:29 UTC, robmarcer commented on src/blog/2023/05/flowforge-1-7-released.md
> +We're pleased to share our progress on enhancing High Availability in FlowForge. Based on customer feedback, our focus is implementing a hot-spare approach for Node-RED applications, providing automa
```suggestion
We're pleased to share our progress on enhancing High Availability in FlowForge. Based on customer feedback, our focus is implementing a hot-spare approach for Node-RED applications, providing automatic failover between instances for improved reliability and availability. We've identified our initial set of tasks and changes to how we'll run Node-RED instances with the k8s environment to create a more robust system. For a detailed update about High Availability you should definitely checkout our newest [Article](./....) about High Availability.
```

2023-05-10 13:29 UTC, robmarcer commented on src/blog/2023/05/flowforge-1-7-released.md
> +### High Availibility
```suggestion
### High Availability
```

2023-05-10 13:31 UTC, robmarcer commented on src/blog/2023/05/flowforge-1-7-released.md
> +Users receiving an unauthorized error when attempting to switch to a team in which they are a membe [#1845](https://github.com/flowforge/flowforge/issues/1845)
```suggestion
Users receiving an unauthorized error when attempting to switch to a team in which they are a member [#1845](https://github.com/flowforge/flowforge/issues/1845)
```

2023-05-10 15:03 UTC, ZJvandeWeg requested changes

2023-05-10 15:03 UTC, ZJvandeWeg commented on src/blog/2023/05/flowforge-1-7-released.md
> +This upgrade simplifies device monitoring, making it even easier to manage your devices effectively. This new feature offers an intuitive, user-friendly method for users to keep an eye on their devic
```suggestion
This upgrade simplifies device monitoring, making it even easier to manage your devices effectively. This new feature offers an intuitive, user-friendly method for users to keep an eye on their devices' status and evaluate the health of their team's devices overall. Creating an overview of your fleets health however large your fleet might be.
```

2023-05-10 15:03 UTC, ZJvandeWeg commented on src/blog/2023/05/flowforge-1-7-released.md
> +[See details on GitHub](https://github.com/flowforge/flowforge-nr-launcher/issues/110)
```suggestion
[See also our documentation](/docs/.....)
```

2023-05-11 08:38 UTC, ZJvandeWeg requested changes

2023-05-11 08:38 UTC, ZJvandeWeg commented on src/blog/2023/05/flowforge-1-7-released.md
> +title: FlowForge 1.7 Now Available
```suggestion
title: FlowForge 1.7 Now Available with Remote Node-RED Editor Access
```

2023-05-11 08:38 UTC, ZJvandeWeg commented on src/blog/2023/05/flowforge-1-7-released.md
> +subtitle: FlowForge now supports access to the Node-RED Editor on devices
```suggestion
subtitle: Further improving fleet management and maintenance of remote Node-RED instances
```

What about this for a title / subtitle?

2023-05-11 08:38 UTC, ZJvandeWeg commented on src/blog/2023/05/flowforge-1-7-released.md
> +FlowForge 1.7 adds new support for accessing the Node-RED Editor on Devices via FlowForge
```suggestion
FlowForge 1.7 adds new support for accessing the Node-RED Editor on Devices via FlowForge.
```

2023-05-11 10:13 UTC, hardillb commented
New contributors

2023-05-11 11:43 UTC, robmarcer requested changes

2023-05-11 12:28 UTC, knolleary approved these changes

2023-05-11 12:42 UTC, merged