blog: Remove feature flag for comments
flowforge/website pull request #814
Opened 2023-06-02 10:53 UTC by ZJvandeWeg

## Description

Remove feature flags for comments on the website

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2023-06-02 11:09 UTC, ZJvandeWeg commented
From: https://deploy-preview-814--flowforge-website.netlify.app/blog/2023/03/flowforge-1-5-0-released/

![Screenshot 2023-06-02 at 13 08 12](https://github.com/flowforge/website/assets/2529595/ea055f6f-f44b-461c-9b03-d70076b5b7e0)

With a comment:

![Screenshot 2023-06-02 at 13 09 26](https://github.com/flowforge/website/assets/2529595/36a2c7df-8d3b-460a-a195-ccfd07e119a6)

2023-06-02 12:18 UTC, joepavitt commented on src/_includes/layouts/post.njk
> +                        discourseEmbedUrl: "https://deploy-preview-814--flowforge-website.netlify.app{{ page.url }}"
wasn't this meant to be `window.location`?

2023-06-02 12:21 UTC, ZJvandeWeg commented on src/_includes/layouts/post.njk
> +                        discourseEmbedUrl: "https://deploy-preview-814--flowforge-website.netlify.app{{ page.url }}"
It could be, though does this work? The difference for me is that I've seen this work.

2023-06-02 12:22 UTC, joepavitt commented on src/_includes/layouts/post.njk
> +                        discourseEmbedUrl: "https://deploy-preview-814--flowforge-website.netlify.app{{ page.url }}"
That's fine, just thought I remember you saying that this technique wasn't working, hence the switch to `window.location`

2023-06-02 12:34 UTC, ZJvandeWeg commented on src/_includes/layouts/post.njk
> +                        discourseEmbedUrl: "https://deploy-preview-814--flowforge-website.netlify.app{{ page.url }}"
@joepavitt This change needs to be applied before we merge though

2023-06-02 13:31 UTC, Pezmc requested changes
These changes have had a not insignificant effect on our website performance, the main issue appears to be the thread-blocking loading and parsing of the Netlify scripts (over one whole second dedicated to just Netlify).

If we're set that we definitely need this feature, I can look into applying any of the previous tricks used (master issue https://github.com/flowforge/website/issues/401) to see if we can pull this back a little, but the net change will still be negative. 

### Before (after move to Netlify)

<img width="985" alt="Screenshot 2023-06-02 at 15 38 46" src="https://github.com/flowforge/website/assets/507155/3bfd32f3-99a5-406d-b69a-2035f38427a2">

### After
<img width="989" alt="Screenshot 2023-06-02 at 15 02 52" src="https://github.com/flowforge/website/assets/507155/dfca866e-6837-4ecb-ad63-5b95b481ad26">
<img width="952" alt="Screenshot 2023-06-02 at 15 02 57" src="https://github.com/flowforge/website/assets/507155/dc011a6a-f257-481e-abad-3569eb7a8c60">

2023-06-02 13:34 UTC, ZJvandeWeg commented
@Pezmc 

>These changes have had a not insignificant effect on our website performance, the main issue appears to be the thread-blocking loading and parsing of the Netlify scripts (over one whole second dedicated to just Netlify).

That's the netlify bar in the bottom of the page though, I assume? Nothing is done through Netlify by this change, it would be community.flowforge.com

2023-06-05 07:34 UTC, Pezmc approved these changes
Thank you for the explanation both!

2023-06-05 07:35 UTC, merged